#Data Cleaning Housing Dataset

#STEP 1 - Import Library

Mengimpor library yang dibutuhkan untuk proses data cleaning, yaitu pandas untuk manipulasi data, numpy untuk operasi numerik, dan scipy untuk fungsi statistik tambahan.

In [1]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import winsorize

#STEP 2 - Load Dataset

Dataset housing_dirty.csv dimuat ke dalam DataFrame menggunakan pandas agar dapat diproses lebih lanjut.

In [18]:
df = pd.read_csv('/housing_dirty.csv')

print("Dataset berhasil dimuat")
df.head()

Dataset berhasil dimuat

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   Bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    YGY    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  Sedang

#STEP 3 - Eksplorasi Dataset

Eksplorasi awal dilakukan untuk memahami kondisi dataset sebelum proses cleaning.

Pengecekan meliputi:

* Struktur data
* Statistik deskriptif
* Missing values

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            130 non-null    int64
 1   luas_m2       112 non-null    float64
 2   harga_juta    113 non-null    float64
 3   kota          130 non-null    object
 4   kamar         120 non-null    float64
 5   tahun_bangun  130 non-null    int64
 6   kondisi       130 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 7.2+ KB

In [6]:
df.describe()

               id      luas_m2    harga_juta       kamar  tahun_bangun
count  130.000000   112.000000  1.130000e+02  120.000000    130.000000
mean    65.500000   267.627679  8.856325e+05    3.433333   2062.638462
std     37.671829   885.664181  9.407144e+06    1.776283    701.684043
min      1.000000   -50.000000 -5.000000e+02    1.000000   1890.000000
25%     33.250000    87.050000  3.450000e+02    2.000000   1991.250000
50%     65.500000   193.800000  6.550000e+02    4.000000   2002.000000
75%     97.750000   280.675000  9.550000e+02    5.000000   2011.750000
max    130.000000  9500.000000  1.000000e+08    6.000000   9999.000000

In [7]:
df.isnull().sum()

id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

# STEP 4 - Menghapus Data Duplikat

Data duplikat dapat menyebabkan hasil analisis menjadi tidak akurat.

Oleh karena itu dilakukan penghapusan data yang memiliki isi baris yang sama.

In [8]:
print("Jumlah data sebelum:", df.shape)

df.drop_duplicates(inplace=True)

print("Jumlah data sesudah:", df.shape)

Jumlah data sebelum: (130, 7)
Jumlah data sesudah: (130, 7)

# STEP 5 - Normalisasi String
Normalisasi dilakukan untuk menyamakan format penulisan data string.

In [9]:
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()

df[['kota', 'kondisi']].head()

    kota kondisi
0  Jogja    baik
1  Medan   bagus
2  Depok    baik
3    Ygy    baik
4  Medan  sedang

# STEP 6 - Menangani Missing Values

Missing values ditangani menggunakan:

Median → untuk data numerik
Modus → untuk data kategorikal
Metode median dipilih karena lebih stabil terhadap outlier.

In [10]:
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())

df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())

df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

print("Missing values berhasil ditangani")

Missing values berhasil ditangani

# STEP 7 - Menangani Outlier

Outlier adalah nilai yang terlalu jauh dari distribusi data normal.

Pada praktikum ini digunakan metode IQR (Interquartile Range) untuk membatasi nilai ekstrem.

In [12]:
for col in ['harga_juta', 'luas_m2']:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower, upper)

print("Outlier berhasil ditangani")

Outlier berhasil ditangani

**Penyesuaian Tahun Bangun**

Dataset memiliki beberapa nilai tahun bangun yang tidak realistis.

Nilai minimum tahun dibatasi menjadi 1950.

In [13]:
df['tahun_bangun'] = df['tahun_bangun'].clip(lower=1950)

# STEP 8 - Validasi Data

Validasi dilakukan untuk memastikan:

* Tidak ada missing values
* Tidak ada data duplikat
* Dataset siap digunakan

In [14]:
print("Total Missing Values :", df.isnull().sum().sum())

print("Total Duplikat :", df.duplicated().sum())

print("Shape Dataset :", df.shape)

Total Missing Values : 0
Total Duplikat : 0
Shape Dataset : (130, 7)

# STEP 9 - Export Dataset

Dataset yang sudah bersih disimpan ke file baru bernama housing_clean.csv.

In [15]:
df.to_csv('housing_clean.csv', index=False)

print("Dataset berhasil disimpan")

Dataset berhasil disimpan

# STEP 10 - Mengakses API JSONPlaceholder

Pada tahap ini dilakukan pengambilan data dari API menggunakan pandas.

Data JSON kemudian diubah menjadi DataFrame.

In [19]:
url_api = "https://jsonplaceholder.typicode.com/posts"

api_data = pd.read_json(url_api)

api_data.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

**Preview Dataset Bersih**

Berikut adalah tampilan dataset setelah proses data cleaning selesai dilakukan.

In [20]:
df.head(10)

   id  luas_m2  harga_juta        kota  kamar  tahun_bangun      kondisi
0   1    297.0      1084.0       jogja    2.0          2000         baik
1   2    254.0       761.0       Medan    NaN          1995        Bagus
2   3    249.7       895.0       Depok    NaN          1983         baik
3   4     49.7       178.0         YGY    5.0          2013         baik
4   5    133.4       424.0       Medan    5.0          2004       Sedang
5   6    153.3       814.0     Jakarta    1.0          2006       Sedang
6   7    114.3         NaN     jakarta    3.0          2011         baik
7   8      NaN       333.0  Yogyakarta    NaN          1989  baik sekali
8   9     81.2       307.0  Yogyakarta    1.0          1996       SEDANG
9  10     69.1       237.0     Bandung    5.0          1980         baik